global:
  scrape_interval: 15s
  scrape_timeout: 10s
  
  external_labels:
    monitor: 'edge-device'
    environment: 'production'

scrape_configs:
  - job_name: "sensor"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["sensor-service:8000"]
    
    scrape_interval: 15s
    scrape_timeout: 10s